kind: Secret
apiVersion: v1
metadata:
    name: publications-service-secrets
    namespace: production-apps
stringData:
    APP_DEBUG: ENC[AES256_GCM,data:MQ==,iv:Xt2TJ//nNQI8MlqNqkyBWY5Ma7QWmHnFlYB0MciSENU=,tag:bN+bscVdbnsVeHDHI0c2aQ==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:shJOYQZrlZqEOic=,iv:HLFUhvjz6Cxj0CZxl4ycDzOi++jFmbstWpUJAKb7jQE=,tag:0VDsDfhpSq9T61EIO5sGQQ==,type:str]
    APP_HOST: ENC[AES256_GCM,data:M+is+XtSMA==,iv:TpAGw0iMRwb7dyl2VhAkfekvioqEX3EfI5uCvCKqPf0=,tag:tND6R/PrymLt7u4x3hUHEQ==,type:str]
    APP_PORT: ENC[AES256_GCM,data:XVDQrA==,iv:eLfk9nRODXm6ZPqI2IvXz51VErqeCE+e8qPBqs2hGXA=,tag:2KJJYh4+jw6XoE4VhmH3gw==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:+afNRg==,iv:PromWZlAmT9gjLa8GOzA+mOnm/tvewLz4YG6qt0JE14=,tag:9EZXvT7QvaonsCbpbUsZWg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:14bVYuO6k14=,iv:M7TBVM9GBZA1ApUBUSiG6rmcqgNdbfQOG6wsraOG/a8=,tag:S6EDHM7nZ5zu4d7zZWsDMA==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:PJulMWWA1w==,iv:aEw0roJoaKY98kY4sStBPdITa8M7060HN5kIGaaPWbg=,tag:X9APozWKWBG6Bfg8g6K6nQ==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:WG4m/w==,iv:Dr5muaBH/RhIENN21EF3fxazhwBrbfeHWHZqmXqOdCs=,tag:+JhMDNq8KxLaorHf6l1AVQ==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:mxwudBegWqRJmbU7MVmqyFIknbw=,iv:3mXRPr7EXJV64IUBQYV2+guYQY/DEHam4uI68+A1PXo=,tag:s62YmGHpoXda9rLsNUxXtg==,type:str]
    STORAGE_PORT: ENC[AES256_GCM,data:trwe1A==,iv:rYguN9V7zevb+/blVejOgyp20S3jT+q0VvPy8ie34lc=,tag:cMvQdsuTYGnuEjqkDDrcqQ==,type:str]
    STORAGE_HOST: ENC[AES256_GCM,data:zXTMGIwcxMHENylO8DfGOmVK0WmDIcIwJ/XHUktk,iv:5xU/i+Gc0o5C9aHA9m055GAnUMLfaEjew4zPcENSpjs=,tag:+qlYjSZCw4x2thuiQcsoiA==,type:str]
    STORAGE_USER: ENC[AES256_GCM,data:3HrWTQ==,iv:SeA6yKZDrI6DrXh6diTvydSDCYAARo1nQT8ECHJ2Ams=,tag:rJFicULhghIEs0PP81P6LA==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:aqqpzi4/Uz0=,iv:QmSH/GdlA/ZRjv3HvhxkvsaM4gC8bSpKGZfSv2uG/b4=,tag:q0HtgQxt+4chMLtTf6yvmw==,type:str]
    STORAGE_NAME: ENC[AES256_GCM,data:qTfsX+Nghrw90ceFfgsCcsPIt5o=,iv:m95MTNcf4zB7Igw9tkAk8z229jvlP/JoiP0VFrTJ0CA=,tag:RLNMiNC5T+t+rIEtu3L21A==,type:str]
    STORAGE_SERVICE_NAME: ENC[AES256_GCM,data:RcY=,iv:jezzDBi1c+Tse1e92PWbUbzH442CPJn2lP8XS6GkkZo=,tag:0WMWqWa5CC0JErtLvpjUXw==,type:str]
    MESSAGE_BROKER_PORT: ENC[AES256_GCM,data:dvniQg==,iv:soBmwvNUtPvAQuXcR0GPEVemDlaSoQ017TE5fHU1pNY=,tag:PWP65jXOZh6T+FogsPM2jg==,type:str]
    MESSAGE_BROKER_MANAGEMENT_PORT: ENC[AES256_GCM,data:eQgiOfY=,iv:R5cr7ONF+c/fB5EvLVeFlPSrAdu1hOb6gZJXKeFtifY=,tag:LZ28Pe1D9nVaLldAdc99Lg==,type:str]
    MESSAGE_BROKER_HOST: ENC[AES256_GCM,data:Me4ZXpAkZg==,iv:FSuGpbGNvKQ8gMZd8240CMTeNJ6gy2pmMYRSVasMwyI=,tag:Ps26WHYkM9JT+dYr1SQ3jA==,type:str]
    MESSAGE_BROKER_USER: ENC[AES256_GCM,data:8u7HNw==,iv:Z1Uf9D/8lhJ7V83NTbRcbOWUf6/PHuUwrzrncnNx+uE=,tag:ipf/7kmnUmD6HZSSZ+zaRw==,type:str]
    MESSAGE_BROKER_PASSWORD: ENC[AES256_GCM,data:ZZifHQpqGQ0=,iv:2BfJ65J3k3paE6jPVpZZ/DHHoXtqOorm9xOfkT0IurE=,tag:DQhsHDymm82lLt9RWy5dsQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:2Yp3bZ6qAjS70/iZMlyFP/rOLdPHB3NtaHn+tU2Fosc=,iv:9kvR+fBuupo2LaPl0Fklj9MMW9KZ09Wc72Ssjy8jZ6A=,tag:tdi4BGzVKRDxMJbq+P9xaw==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:f/1UJF4=,iv:X9mitBUoBXwNJdTI+dCUCXCnaOHBNYnWEoj39tH8nYI=,tag:hKrAxbouDv1lLTEXoVKq8A==,type:str]
    LOKI_PORT: ENC[AES256_GCM,data:S4lk/g==,iv:hQ6UqVgQZpx8E5JJuU2yzotE5+EeGdhjFlDwiE9I55A=,tag:YgEzlPAUKE3S//6+HA2iJg==,type:str]
    TEMPO_PORT: ENC[AES256_GCM,data:gOruXw==,iv:8klyHWOoasZIRuxgok5jNinEOuQQ9rfQslitHTlGV1k=,tag:ZjI+ftEjiagibHtctNmOUA==,type:str]
    TEMPO_RECEIVER_GRPC_PORT: ENC[AES256_GCM,data:ktWuEA==,iv:7vurf+mkYTfKovGt4PBYWwTzZvV1kd4xYL97hzNbaak=,tag:oioP3SyyYBZ0m3EFVroywg==,type:str]
    TEMPO_RECEIVER_HTTP_PORT: ENC[AES256_GCM,data:2dsIiA==,iv:F2GlSZrln6fn213wj9Hzh50PBVI/SDglZ8vb6llMFms=,tag:6JpAjG7gGpunMDqjKxHr5Q==,type:str]
    ALLOY_PORT: ENC[AES256_GCM,data:eRhNPF0=,iv:iuRLw/bQGuZulGH0GtePAc1slPVFACWmSIarqP43wXU=,tag:KdMBR+j3I8iZSrkVxMJ/uQ==,type:str]
sops:
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeUpIRCtRS2FpT3VPd29m
            ZllLRnlKUlc3M1BCUGtPMVpSYlpkTWJ0ZzNzCjkyY1JIdzFUZ29xUUhSeWQ0dVpX
            U3JRMm5KaGU1M09sN2ErN3RJVmFzUnMKLS0tIDh2cDNsamR5a25teEcyaDFBdGM2
            MHRHOGg3aVdqWlZOL1FEN1Y1ak9vMEkKSdKqKUOCbPED7VjOhhuy8zaOPl1V9pCB
            256DZfHZOKuiZuOY6naEVXh84JdUti9RS4q+AvQDfbTubD6WV6jeZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T18:53:42Z"
    mac: ENC[AES256_GCM,data:vuznhIgH/kGXnUKR9vmYp+BdBG4qUnM6pLg7aqOozk9J+sD7sxfN3E3eMFnB+8jbn+3iVRz9LlTN249RKth1SOcZbFy5EAHQ1sAoRawwCMpXFbSqfwAZSu0MTnv2/sI2DARc7LoYLR44yKyNz4Sm8RcY4AdHkRg8geXkaH946/8=,iv:OpJ7eebHyVn+m6i7dRPH1fOOGwvnsEk81EoVqgva2KM=,tag:L37+VrBH8rmfOZO9j9EvsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
