kind: Secret
apiVersion: v1
metadata:
    name: publications-service-secrets
    namespace: production-apps
stringData:
    APP_DEBUG: ENC[AES256_GCM,data:0w==,iv:H18KpZTJoXfM0CXvxOeaI1nB5qLO2RIcgQ0o/Hkiy34=,tag:lXCijTxoWLQPGyxGz0V0zA==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:udQeXLQS8jjdEQ==,iv:arbpL7EoomkM+ifNUFQb04ij8RhMYn0fWQ62Mzls0FI=,tag:win5UOF3FC6L/blIZ+MHyw==,type:str]
    APP_HOST: ENC[AES256_GCM,data:j9p0KTLHROsAZQ53aQ==,iv:zsiW/IQ53N9jMaRYf9qf1IQgMEVKrx7TRGVyhNlYjxY=,tag:mQlRvq+qKrwfB5H56GwizQ==,type:str]
    APP_PORT: ENC[AES256_GCM,data:hf6Fyw==,iv:0f8X4tY2de1qLEpUtwX9g8wm+mFeuoUHILNKw64+uA4=,tag:cSwumwwAAuZyndDaKrzaMA==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:PQihSg==,iv:mQ1uP8naSY5IZf7k4/kKjdUGwpnNPR4s4SHyA9SadE0=,tag:9iQvR3M00VPSEk8Em/1s8w==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:Z7bO24BNEuU=,iv:v6e1VwokcbXtJfUbKMWd610QoJBC64cjCC5E7StDGy4=,tag:WH9hG1mLIJfWEQqXA96d6A==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:/hycW7HsNk7HnJI8Ig==,iv:NC1moZSvmPU33gaLkA17KDkfvQtIa06qnXqsmhSmAuY=,tag:xy+SFtWDo06Oqwkkm8t6OA==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:hAOwbw==,iv:LgNE/g+DZz8Y72WuKzS9DInNQcHNTbPQcIgyWeZk64c=,tag:ofVUIqkjXIcM4taG0jTyJg==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:eZpWkIx5jm7Db6UhE1kwwN5IijE=,iv:sZbT1KLSGb5nfRV2k8nQAnT4adfWG4+JSOe7phB8e54=,tag:wV/CQbKpTbgiLQI0qD1D6Q==,type:str]
    STORAGE_PORT: ENC[AES256_GCM,data:SDEufQ==,iv:cjuW/e/aes7davPltNBN9HOeFFkYN3O435ZG1u3imuM=,tag:7E6UDO35eIcEvk7cO+bmTg==,type:str]
    STORAGE_HOST: ENC[AES256_GCM,data:nmeL2Xy3mkBACyNL88oO6iHRaxE=,iv:FURWHTqacDUB30IL2SRYMI4qAb1goSOfh7LpPYYsZPU=,tag:PTf5+1mxr2HiAifQq1p0/A==,type:str]
    STORAGE_USER: ENC[AES256_GCM,data:X0gxPg==,iv:OQ4QwByI0Cnh8/WJsC9ng/URXQZZT9vH4JS16y1GIEw=,tag:FWzWODehyTXwjUmwq9OBsA==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:xX2LYFT0RF8=,iv:KkqF7OIJBKOQ4cQbZOFb5+VYlc2GxCXBN4bOf7KVEfg=,tag:yJ+zecLjyw9zK5wcQoAQSQ==,type:str]
    STORAGE_NAME: ENC[AES256_GCM,data:OU1TY7NqWPJEEP/p93Vgdyhv4fQ=,iv:GGH8k+MmPXTeNCaSrZyZWqkUlthX60cJAX7Qkf3kGUY=,tag:VUH7N9ndiBl6MBu2038QpA==,type:str]
    STORAGE_SERVICE_NAME: ENC[AES256_GCM,data:bdo=,iv:5FL5/tt7hsRuedU7rTvz2L3wF3LNTouK6XH/DjuO0H8=,tag:7gti0QNH0rcEQvkBhUkmNQ==,type:str]
    MESSAGE_BROKER_PORT: ENC[AES256_GCM,data:NcM8jA==,iv:2fnc50r7k/08DjJiRJuplzzGlaHcF51XLCRpNIbUxXM=,tag:Kqvzsb2d3i0/Oqofb6Cxng==,type:str]
    MESSAGE_BROKER_MANAGEMENT_PORT: ENC[AES256_GCM,data:ku88Y9E=,iv:QQksn9H/BYF8NDyCqGAtHWgQp8KoJUuo10WqJUcEANg=,tag:m9yyUffBuCY+TNp6ay0piQ==,type:str]
    MESSAGE_BROKER_HOST: ENC[AES256_GCM,data:K9ocHrIkQq9eqXOZ+g==,iv:TXFpG0MoLYdIwlQ12yIX0OSlLsHAz/BpUEJpST5AMhA=,tag:psN9wUn5brgIjK026fKQgw==,type:str]
    MESSAGE_BROKER_USER: ENC[AES256_GCM,data:ue1wEQ==,iv:IP5SK1vbeV4JYm8VuB49Gx8GtdjhIvQ17qErXHgNY74=,tag:XVeZeYwJTd5fczybmw4TIw==,type:str]
    MESSAGE_BROKER_PASSWORD: ENC[AES256_GCM,data:9qdNbA9d77U=,iv:KyucyjwMi4STNx197FqrrGS2LTANsWmbs1Xprfr4re0=,tag:XdAdXCTd3XejntXMPCUzpA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:oeUF//sczCghxa2+UmncugdbRXNSNRk+YufPjWGsNdY=,iv:qudtou1cJ2jV+cfj/+qXY3SBGOHLpRc3G4H2A0j6GWU=,tag:En7dmMgDS43gmZLkS5LO/Q==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:yJF6IVI=,iv:kxr9FEVh2GLxOImhFGwWEFEGxqn3IfTef6UFNPwNtss=,tag:hOSYhIWrzHM+O/3PirceJA==,type:str]
    LOKI_PORT: ENC[AES256_GCM,data:s07a1g==,iv:JJxhEjhmEOOhgtJ1UA4fW5cN7B1LHXZxP8AjXn/JVjg=,tag:/Iu+JIXxUudUBzVVc8Norw==,type:str]
    TEMPO_PORT: ENC[AES256_GCM,data:/f/+Tw==,iv:E6RT2K8Ormuvwb2rd3XRQ0xZlkH1m2x5wRl7BxK5qxk=,tag:98j5GYLfYScQycLIr0R9dw==,type:str]
    TEMPO_RECEIVER_GRPC_PORT: ENC[AES256_GCM,data:sfVhpA==,iv:4WocXIZ1JuAaGWuochVRsGgG3kkqLThSZuTSdxdM+hQ=,tag:tqxJBm0/jPlzKGhnj5fuOw==,type:str]
    TEMPO_RECEIVER_HTTP_PORT: ENC[AES256_GCM,data:uYu47g==,iv:U8bnM/j+Y/ad3tpci+biAMWqEv8BOIxfscdchODrTvA=,tag:xmfNJfjiMWnl3zYTVqz0Xg==,type:str]
    ALLOY_PORT: ENC[AES256_GCM,data:mA69/5k=,iv:wvGnTqRuYOG2SM9HQbTpTPl+g7NRc8vaiS5A5EGHFKg=,tag:uE+eBAkWODWAMRhe1ag5tA==,type:str]
sops:
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdVdzN0U4NHRZTWF3ckJ5
            c3FSTnVLbmh0cjNJcXdDQVdNVXJsQzhSUVJVClBKaG1JOTM4VVgzRUhManNTSTZh
            UUtpcjZ5WHZ5TDlGMUZyRTE3b3d2RFEKLS0tIDArd0ZtMUFvbHZZdHZYc1dwdDRV
            RDAzdCs4TEdUZ29kZnB0czF6K2hYM0UKTR782gg8Jzy2vRJMlk+vvDpKchE5hRFt
            8P9CocdYOC3uewAyDtWrGAgJtrhaCqD7VpYIyCREYHoQOYyvw8T+sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T21:01:08Z"
    mac: ENC[AES256_GCM,data:hniZb6o/WcjsSRjrVGnwteZkW4+3ZqEg9KHcAApFakIJjdfLp9jjiXQ+TBqbLMv32tK6y/rJjKEXaanaCNgNiTB7GfKa84QsFJ70msZAAEOw0/4SJXFXFNq8Um8Q54mq5912or7Jbi9eePugAuTJsVuyNepgvecBzTdu8UJrTjU=,iv:inzA+WutsYU46pA4jD2BqijaSetnr75C8XCV7c1jg04=,tag:SYj98MAE+wDLlsrPSMXB3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
