kind: Secret
apiVersion: v1
metadata:
    name: publications-service-secrets
    namespace: production-apps
stringData:
    APP_DEBUG: ENC[AES256_GCM,data:pg==,iv:lQNNrp5RiWdClsd/sE4/W27vp96ZGP7B3EwwatDls6E=,tag:/8p6rgTErouul4fjSF7flg==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:3nclHbJ4g4kvvA==,iv:QvuURiDjTSVrk1M7ha1yksk2ul9I/K+C38ukepMnDao=,tag:rc5y8PUUn94SZR/phVb20g==,type:str]
    APP_HOST: ENC[AES256_GCM,data:EGsMl7+xDzM9DUBkLZp5jP45Jga7D9QzSofNBfQ0ekCmzlM7pQ==,iv:Zm6KmwRLejOtfZ/tr+st85gTwD1YJEOTPfzoK3AVx4I=,tag:RzKmxon2eK9UmF5OyRv8uw==,type:str]
    APP_PORT: ENC[AES256_GCM,data:8pRXgQ==,iv:YRcaGJK65ijGYFPbZUCCukbcCVm1spLGQ3oi29NxyGg=,tag:SdiTmpYyVmzjSYxexff9ig==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:j2BW+Q==,iv:As7ufmb5F68isVy+zSx7rKMNnGYU0iv1MIqmpiE/dcs=,tag:O9olK7S/jiYJb5ovqaph7g==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:Hw4XjPDscwo=,iv:8ac0oTuacw6+eoezlY68yne+dezSWyqwsF+B4L6xLv0=,tag:ZLWbrvv7Xg7bZQE03JBo5Q==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:nIbvgkFyyLREZeUXVpqDbaPwmBxiMMQ/jb+Ra+lJxSX1OZi8PQ==,iv:V0BHH/ZhkYJ9jDF1jesYxvkjxlVKzBeJJoY0XW9iJfw=,tag:n8JhiBpZ/p0GtbIbk4iJcw==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:aIhGAA==,iv:A0NBn/ToMQEcFjhl0Hd6cD0e5sLiCtFGDh3es+6RGOc=,tag:RwWAEL2sTFxh9e7Mh2lN7A==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:NtspLaOeHcQb8EdcHCiT/PqjPuo=,iv:PhverzH/GC0Lb7vWWpdQgcX7lPmP1kb/abm459Osnjc=,tag:ZSqbZc/pyJQNeu5qiUnLGw==,type:str]
    STORAGE_HOST: ENC[AES256_GCM,data:IwjwT61eIZw9yX6nVnaW25fKOnRh46RKIUmN8omjuC9nHvK7f+k7Omhy1oLc,iv:OrAM3eSYmPTPGImF/jwMWTMICUo7zRJg96EJWmVc+9s=,tag:oWtpj4wz1H9f4vyliMCArg==,type:str]
    STORAGE_PORT: ENC[AES256_GCM,data:0dC9FQ==,iv:ZkQ7wcD7MbMXOo4vzHV+KDAOWSqnyZ4toHXKDP2YgZU=,tag:g5oZzGVH7Z+hBeik61oWrA==,type:str]
    STORAGE_USER: ENC[AES256_GCM,data:VQ0WEw==,iv:UwH1jNHt65pVGyr8ErJj81Qohqxx3+cSOLRY5h3ARig=,tag:77ZOzIXy1kEzgd9lTrZUng==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:i/jxaS5O2j0=,iv:4j6VzVP34+nfBABugb1+rM1HTZfeSPGNJE2xz6MK/nI=,tag:ZPtnevdIZhpkSPtF8Klo4g==,type:str]
    STORAGE_NAME: ENC[AES256_GCM,data:Q3TDNtyCAuAjkJtBA/h1e0N5bnU=,iv:dAgVNYpqPtuEmvE2G6fqpiZRHwVuNxtXfnfr5lX2ln0=,tag:dJu7SMp2mCXrRZ04sYmfAA==,type:str]
    STORAGE_SERVICE_NAME: ENC[AES256_GCM,data:iEs=,iv:cxa5WKG3CUed1jme2BQ1Lf51WsjcBQ/suY7ljwlRWng=,tag:U45XTHN810N3qmfrQS0LRQ==,type:str]
    MESSAGE_BROKER_HOST: ENC[AES256_GCM,data:vv1/BkFqK5xUr+riDAGVOVipliCASScUv9B/sn4p6m3aKbRo7w==,iv:U8fcSk1ryiK+YwcSuNmRHzmteQziSpQsvSBYSNyOBm8=,tag:nL9a/XBJz8/UEcs6EpEw3Q==,type:str]
    MESSAGE_BROKER_PORT: ENC[AES256_GCM,data:UlW4ug==,iv:2hQXIw+xUN13LoD+lunlaau4aC7mHnbJgHmqqfCoAx8=,tag:FmNaCGGZjtDMOlgWhGORNA==,type:str]
    MESSAGE_BROKER_MANAGEMENT_PORT: ENC[AES256_GCM,data:dIIwwKc=,iv:xMygiODOBo+RYcJUrq77WXElEkpVHW97rOZ0+h51NqM=,tag:23AxUMvhsreX+TVSdqV3bA==,type:str]
    MESSAGE_BROKER_USER: ENC[AES256_GCM,data:F8WYhA==,iv:FxJtzBRaXX+usNp6jYvYTkG/ZpPhXCaN9dfPtPRlxZs=,tag:tBj5NC+LG4ML0kCRiJh5vQ==,type:str]
    MESSAGE_BROKER_PASSWORD: ENC[AES256_GCM,data:kjaSQpGgWYY=,iv:4j6OJ0vAIKfKSazq46fFrnbOd7owonuSDaXqHMWIu9U=,tag:xta1XULTvBmipXxn8SRO/w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:cc07DnHtUcLajYXw+nfzRM8TdoOe588G1kpbIusvfNA=,iv:gvtJ4/+IBLAb2NY50US82WPR9KUqDncMmg49OnASwdA=,tag:1kt3aezWw4UrVChvtEE51A==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:YxV33GA=,iv:O5iIqy52FdQw81/TKACvNniqQTTMt64K3x+kjSswyKw=,tag:UixrWn3KFCVY2WHKPHJP+A==,type:str]
    LOKI_PORT: ENC[AES256_GCM,data:XT1GjQ==,iv:JM8mEma2gsIl+0zU4rYtiElWPSRQ9Ca3iALYkGLdo38=,tag:fnYnwvxh8NpZDxCwlwy8Eg==,type:str]
    TEMPO_PORT: ENC[AES256_GCM,data:Fvkvog==,iv:h+z0TsifATg+l/Js6KH6JBdX+bMTG2fcgDUXZq1PRHQ=,tag:TpH1597PTFNkG8NdYZ4mmw==,type:str]
    TEMPO_RECEIVER_GRPC_PORT: ENC[AES256_GCM,data:SeXBHw==,iv:EiwguprAFP1iXNei/Egua3G9PhlLIat0oLQ+UwS6KWo=,tag:leaW4hP6Z08+NhbatNL2Rg==,type:str]
    TEMPO_RECEIVER_HTTP_PORT: ENC[AES256_GCM,data:pDtBpw==,iv:BZvXhkxWeoN6i/7xOqg/drB6KjFeKK5w9YWO41xxPU4=,tag:BAz1W5vy2lICYh6bd/qjyA==,type:str]
    ALLOY_PORT: ENC[AES256_GCM,data:fAyCkwc=,iv:HIeEommUwCHzVAEY+EvBo4P/MoyN/h6mHoNA52Flvdc=,tag:NJHJOL8SypBuWyEptV8r1g==,type:str]
sops:
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaStNM04vQStrb1ZLemhQ
            VU0rNUIvSEY1Nk4rd0ZJL2cvRjdmdE81UFZJCjBKRkFxV1E2MkFQSDFpQUJmUS9W
            REdxMlNQaWljUUJ3R1NRME8vR2hRNG8KLS0tIEM3dE5HMlpMblZRdlc5RWZpVTBs
            TGZWMCtrMldGMm1OS05TbHJVMWZ3OVUKpiNdNXkE+bCCy69E8aeAPHoQQeqgQ6Gh
            vZZNbmcfdGK/Cz1YHMo35GiF6veOIHHr94nKB4ww6F7eV73zpsPFDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:36:56Z"
    mac: ENC[AES256_GCM,data:NnRzoKKaAt75+kEWDqJX3uW55v5OT1ZIMSS4OkCZ8vFTxrL3qI5qlG539qsmNzbwhCuc/bCpgRhap40wbQBQ5hmcFCIZ0bq8mIk49+WWHV1AIBdJRKUYGCu1EH3lQyekZH7vO3bIqi9HhzocvDmFaGj2mjgAPEdeEE5yGT+H37k=,iv:BaDvHUA0ifp5f6MWuByL2wE3lHtOh9JyHqomGLuY06M=,tag:rLKNarqn4bVZVzgG+gKrZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
