kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
metadata:
    name: publications-service-kustomization
    namespace: staging-apps
resources:
    - service.yml
    - deployments/app.yml
    - deployments/worker.yml
generators:
    - secrets.yml
generatorOptions:
    labels:
        deploy.type: kustomize
    disableNameSuffixHash: true
