kind: Secret
apiVersion: v1
metadata:
    name: publications-service-secrets
    namespace: staging-apps
stringData:
    APP_DEBUG: ENC[AES256_GCM,data:0g==,iv:F7Es1hUQyv6mEkG8O/+xtvav2AubAKEF/X/s79FCTiU=,tag:YQXpXFVx9x7RlLrc3fZEzA==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:TF+cuoJ1Lw==,iv:zcoRPKr2uZTPtLKIEdKfzyZGzBGzETMkaTBL/j0YRUs=,tag:1WqTCVBq91opEvqlMFDYfA==,type:str]
    APP_HOST: ENC[AES256_GCM,data:syK6m2yzQA==,iv:iYeI943lbFSKftVInZ1HWgRq0l2aT80JdSKrVSqZWNk=,tag:Y5lfoDxfdjBhHp8cOOUWKA==,type:str]
    APP_PORT: ENC[AES256_GCM,data:1mqTWw==,iv:EUNAnJvI8CT3fGfNHR1I42E7/MzSFJvUMwBfGOviUck=,tag:lYNDfLV9bAMpC0Bq4fdHmg==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:sJ3pHg==,iv:/7tfRVniFP+mCogScD8ux+TBraSnzwHPA7Z+us5ExzI=,tag:ouME8SaEePav3djVzSaVtA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:N1loEWKeDdo=,iv:+vY0NJE5BynaI9bnKneBFkNpTIIobkrBqZ9DyUANiLA=,tag:++OeiBNMDgOC2cgI1kiVTg==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:1GOC7MKrLYw3mBWcRXh7n8Nn/iKEug==,iv:uKtGC0qFi312yJvZOY4Qn7z/uDBB2Z1YwhVUCnVpqWc=,tag:a0dDJa3xTG9AEeZRCAA2RQ==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:UjV4og==,iv:O7e8YnBBbEAc+37Cevv4PybYd0YuNm1Gjxze6q8ZvXI=,tag:5P7qzPH+z+n89V5WM6TnxQ==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:aVpW0D6ZwoiuTYtx4lAUhJqEusE=,iv:vheyaAuisGYeJZwsKRBOFJNUuGiTIbHmrYOQnD9z/8E=,tag:1IXsY8f3dUTdEkQbSBDrpQ==,type:str]
    STORAGE_HOST: ENC[AES256_GCM,data:EPxuNicwa/BLgVg6GPlDViX9gnE7ib3+4gQNkMA=,iv:+mbrQpHAuInXFdAKRgt9eHu0bNzgV+UU9+FCKdoOO74=,tag:g360DHYMtv4kPZP3tghDxA==,type:str]
    STORAGE_PORT: ENC[AES256_GCM,data:XInkGw==,iv:m+DZzSDxPKIjhYTHg2IZbksAfhDqfckmxNPYKHy3Rpg=,tag:pnPl2Zpt0xNFe3sgJZYMxg==,type:str]
    STORAGE_USER: ENC[AES256_GCM,data:WWtW8Q==,iv:BEP+DVy4F/aVBkCEHNVwF+jvi+hAEGb2U01srvW+8Ds=,tag:aqNTTDPI8ze8X8P4Uaf9BQ==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:fEJ/zS3/X3c=,iv:wh5xOei/8p1xHNS+KN4gZOJ8ZECB6k5Zsnu1+Kxi16s=,tag:++7DX0GOSMopgI0nWG29HA==,type:str]
    STORAGE_NAME: ENC[AES256_GCM,data:R/Iso6E6Y/1lGaz/XkryAp3yqHc=,iv:o5UnJnweGZnmR4HE4YtmOCCws67TJECDQtvTj21f5P0=,tag:Z82tbkw84lbGdwCZWirAaA==,type:str]
    STORAGE_SERVICE_NAME: ENC[AES256_GCM,data:MS0=,iv:lY3UvXEJwmKe5PJsP7rOk52Hua0niIwsPex8o5S2hKo=,tag:eutg3TikoFmdNsaqRzMG7A==,type:str]
    MESSAGE_BROKER_HOST: ENC[AES256_GCM,data:Gc9MjNQ5R3WQRYX2+G5Agf8xoQR3Hw==,iv:tMeHmE+eUtAn1vhb4NRj8u7YmOz4EMUqSzoGyYYVS/4=,tag:VaAQBSjA+b66wIiL/tRRTA==,type:str]
    MESSAGE_BROKER_PORT: ENC[AES256_GCM,data:1lcWlw==,iv:iQJszg13S+8xc+zgyyV8HL5lhDXGbfwi6xRXytHRmyA=,tag:ClcQxf5sH4PuzEsf2dU8Ew==,type:str]
    MESSAGE_BROKER_MANAGEMENT_PORT: ENC[AES256_GCM,data:e+k/QWM=,iv:ZAE44ux2N/UF4w2CgZFUAy2wPAp4G2NUAeBQqbFIWhk=,tag:Cg8u/4Ds977zJVuatAryQA==,type:str]
    MESSAGE_BROKER_USER: ENC[AES256_GCM,data:BSrL6Q==,iv:m4SNt/3BfNNUEXBipwW3sPKD6aRvBMmjkgTwEGN/fQk=,tag:Km/18zbDcvKP0JkiZ5G/Gg==,type:str]
    MESSAGE_BROKER_PASSWORD: ENC[AES256_GCM,data:+C4he/3/C+s=,iv:56V1shzt4ZJSPmOYqydF/WIa9xM6M4UH04M3IHf812o=,tag:aKJ8NOmp0iW5U42NhDBMcw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Mga31U1n4jBj8nuP/+eb7bDRavysZhRvGdxgXtkCfE0=,iv:waeMTvvcsE9TpiF6mJf0p2LaDtYxmTFjVhvxKS9GYR0=,tag:1JEfgo0N9QMc61V4fjER0A==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:8PfQCJg=,iv:24Jt6Srm2TY9WnPfn5To6EJ+qLNkJ0DUM5Xc2tNZURo=,tag:Bu6DbVrr9Ymkfkie3eqraw==,type:str]
    LOKI_PORT: ENC[AES256_GCM,data:XkFmoA==,iv:jYZFmm64Qoq4GBwyeEVOwlSsqrPTgGAAjSMYBFFqzUw=,tag:Liq6zHLL/wCDTD42xxzKaw==,type:str]
    TEMPO_PORT: ENC[AES256_GCM,data:x/qjKA==,iv:IPurM6n3FXFrZZmaobiXVB5o2c+gHogLpLaOtSfQL7k=,tag:WljByC4KNNMKA2iTvq2cbQ==,type:str]
    TEMPO_RECEIVER_GRPC_PORT: ENC[AES256_GCM,data:nZWTlw==,iv:XT3ZBznAKY/Ezj2ts67adh0bQGJXLDcTZhwbK8Xqf20=,tag:xdDFvWF0W6HtEDumhR0yRg==,type:str]
    TEMPO_RECEIVER_HTTP_PORT: ENC[AES256_GCM,data:XBzTUw==,iv:IEhGxg6WECz43lodiY32fn7p4xoUI28b9aWqxUNfJGA=,tag:k4yRSQBFfZ+Ga3QC0+dgyQ==,type:str]
    ALLOY_PORT: ENC[AES256_GCM,data:dVUfapM=,iv:OMfAaJK4mtAqazEOdnDgZGhhOW9hel76T5FQ75GTwa8=,tag:dYoKOAiuygvIZzyrHgbkXw==,type:str]
sops:
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNUxDTEY4cUpOamhRbWc4
            bUdnMDE5R054RGZuS1pDK3R6SjQvd1VsN2g0ClcyOWluQzc2MSswemFZa2E0M25U
            WEREZG5jRDE4M0NWNnhzK28xNTNpb1EKLS0tIE9jMU5QcEprcy9FVmlUZk45L2tW
            Nm5qUzRWNThIOUhMUnIrWjNFQUpZeWsKQ3ItGlOGSTBQmBj+oIXDAB8RWCvbp36N
            sZQGoNiVghM18WnZeTB1qQhJTmmW5a5TEAXK3Z+DxTqCoe1bEM7ZVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:54:31Z"
    mac: ENC[AES256_GCM,data:RLficPNXdZGu/V2Gfzpvu/5kC16V6JsDVfQx59j0xSJypH/V7uhL8MjpdOlGJUCX2CIrIeJZXDjxBmQ/Hw8LwcBkoEiXtuRqX0Fzt2TgCDhMIyNlTNJsIWQWmFrhQGBe/nTXhDrozyhkJCcj4sngy7wgiRYbVCmKSVoL3PqqpNc=,iv:oJpX3xTvC6RdFRE32PXlWpv4LLEbOYyyTt6yiwVG35c=,tag:1GzPLS5KIvVHIZjctxp2rQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
