kind: Secret
apiVersion: v1
metadata:
    name: publications-service-secrets
    namespace: staging-apps
stringData:
    APP_DEBUG: ENC[AES256_GCM,data:Wg==,iv:kmyZsogYEz9Xm+agi/2uaN/ddFtySs7N43u+M6SrBKg=,tag:XZSjFxy1ugonSRCACx7ldA==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:8YUyObzf+1oNO0o=,iv:UL8Uv7bn2Y3HXlWJc00tlOM9nePvoVwVCVlz6nWN1vI=,tag:r79FGdy8VC8j3nPTc0NCvA==,type:str]
    APP_HOST: ENC[AES256_GCM,data:9jgJBoOCnQ==,iv:TnhbR7aYvpDddmikRWm8EegYti14CCZ48xv+YkE0k64=,tag:2AtTcAOAWkMckFvzsycOJQ==,type:str]
    APP_PORT: ENC[AES256_GCM,data:NEUNFw==,iv:pNWBHap5CqE2g+4Fwi+1thv6Qt5hy1PtBGN1Wmq20cM=,tag:QZvtODWzu/Zgjvc8/tplIw==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:WgR/uA==,iv:aprmKloOI4zhyD5w/eQBWiibKR3D5mXu6gggQ3t3rO8=,tag:t4YU3GSkQiUNuYQK0xsLMg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:CbzVaUKLbmY=,iv:a8Kf59EiwBYEj3kUzcQWcCNKOqZXrfRk8uVUSl3huYI=,tag:k1FjkAiOXI3srazwPr3sUw==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:uwpc5XHy4g==,iv:ZWUUG4y2uaWAEqC75LPEtjEhIdKxo+gt+7wMtBLS2z8=,tag:mxsQLFt2vhXkuwVOgqXmbQ==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:jJ+KVw==,iv:Im/TN7iBDQknRz1Sg+cCAbHi4EP8DK/OkJ8sidI0rsc=,tag:ulszEtEbBhhsDEBRSwN9ew==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:+Gr0Gv12SaxLYPTamPDzl+DAmnc=,iv:A5q2+VGUQuh2NLG9NOgO4G02F3smm2PaK16IgZa7AYw=,tag:hSkgWH0gKPYydUse7GkYyw==,type:str]
    STORAGE_PORT: ENC[AES256_GCM,data:wsdudw==,iv:URlD8RHAWp3ODYx6HEuDJzmmQB8nrQlPSwuYQ3ZS2tc=,tag:I8wCq/0RbAOM7oHimy6Mtg==,type:str]
    STORAGE_HOST: ENC[AES256_GCM,data:yXhh7saSrtttOE8B+tgUKkoIGGrhEHCtyOFDQlW4,iv:MyT3P6EPOxfp0aD77HqYuxO9vCEgAFXfK2co5O80v1Y=,tag:PbcXazogSqddnIwT0LJuQQ==,type:str]
    STORAGE_USER: ENC[AES256_GCM,data:zCbeIQ==,iv:z2uFMOKeHATawxt4f0zDOhYLuCLhawm09OdUZIsJ3Uw=,tag:tRNgz+PRVN7PfzJKcOBpgw==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:dN8otr9P/gI=,iv:HphLWH8FEmAyXc1SphE993w9bxo3LDBB/KqiwccpyNo=,tag:LYtNwU6FxenW7UDUMA/mrw==,type:str]
    STORAGE_NAME: ENC[AES256_GCM,data:r6MmWZNQUtyyXS79bqLRKekpcug=,iv:iYpIM2e7Hkg8TlRnEP9JUW2b2UIcXYgbponLBDfB6YU=,tag:LPJ5th+bp9EufYBdUoRB1Q==,type:str]
    STORAGE_SERVICE_NAME: ENC[AES256_GCM,data:zVw=,iv:3Pz+W1cLc2JgnoLoX64aT4Lz7+v0InJK351h1SrKoAE=,tag:MnDUv+PjPhtK76uXdV0oaw==,type:str]
    MESSAGE_BROKER_PORT: ENC[AES256_GCM,data:I5kviA==,iv:Ox46GSQ55/lcvhP+DFFgWuEYx8o2IDF+nhPh6U5/Wgg=,tag:Bl2qmzIgdtJn8ZCxXbIySw==,type:str]
    MESSAGE_BROKER_MANAGEMENT_PORT: ENC[AES256_GCM,data:2H4VnDk=,iv:Ba6NV2seiBuoD0m6pamis7tQNDMMiDB2EbNs+U/lVYA=,tag:hEo40IKI8t7KB7woaf55aw==,type:str]
    MESSAGE_BROKER_HOST: ENC[AES256_GCM,data:nIGb+LnJqg==,iv:pgPJAILBFOJ/JxVliyXEhX899avPh5qc0GUEW5A8JWk=,tag:Fi/opaGSnY96VCsdiNbkDw==,type:str]
    MESSAGE_BROKER_USER: ENC[AES256_GCM,data:k78XkA==,iv:FnOQEO63D6Eg8+I6mfx/rhmVo7MgN08jkNc0vjg1YJI=,tag:wnhIiqMwGIuH3uuQvHsZPA==,type:str]
    MESSAGE_BROKER_PASSWORD: ENC[AES256_GCM,data:cPmvhkkt2mQ=,iv:CiirjChGLrdgTNAmAtMDM6IvVRRd/PrYyQF7GTHcTXA=,tag:TOEt1tCsMDPR0hzZwMdNfQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:BCV9tF3OAnD/D9jRTZ/SQFuqkwW3vRi4XU3ZHXFveYg=,iv:C63gbbUkJXBsx9ce9k7T9jD38tJVhgeI/dyZObApWLU=,tag:miygKj1Vk+U5iVy7y637hg==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:gcDTZ2Y=,iv:0EyrA4Fou0fkpSTJGeoyYcBc5NbcJLeftRPRP2VrGWY=,tag:Y21GEyFWTPSAs3qKAlXB7Q==,type:str]
    LOKI_PORT: ENC[AES256_GCM,data:DdLZwQ==,iv:HONS61//0D41yg6lR/E1QTJll6i4muNZ+hk49kjL0XU=,tag:6v8+mJJ/pllRJXuzAVR69A==,type:str]
    TEMPO_PORT: ENC[AES256_GCM,data:/DvFIA==,iv:kZ7fXPVTsUJAdqpv2/gt2d4m8Ef7fN2zklK4iGLdf54=,tag:ie6Vwe5ReQN5mrIPh6N0cg==,type:str]
    TEMPO_RECEIVER_GRPC_PORT: ENC[AES256_GCM,data:kkxjbA==,iv:3k6IfeyR7NzxQg8fKAmOLwVvVcVfmIqx6R2HF/s2QBA=,tag:BVGo3OttzT5Xgvr93k+0pw==,type:str]
    TEMPO_RECEIVER_HTTP_PORT: ENC[AES256_GCM,data:gTyMTQ==,iv:0HcpoTf4JsZflwt4JBv0pGfQBwm/6CZ1eDAYDt2Ey6c=,tag:JzIqmZ/z2PRcPDoW85E/Ig==,type:str]
    ALLOY_PORT: ENC[AES256_GCM,data:v4FFTyg=,iv:h0iZ5xXoSLuPxXlpe1vVtMEZM97KE1f2+cyQvv7dG+M=,tag:VVLuhf76HvcDbFAMRRKolg==,type:str]
sops:
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ejNhNlU3MlZNRXdVclhO
            UVRYd1RwS3kyZTlCdktQS3VGOGlaRytQVWpzCmcwZWFyWFh0NytyMmo1SytPMGx4
            WU5EMHFNSHBGR2NlVVlwMVdZcG56Uk0KLS0tIGRUaytlZy91OGJxRkNDTUZYeEp2
            V2psYjVXVkJzeXB6WUo4M3phUVBiTXMKXAzOnmRVSedH0ooqm0PN/lMPhUMsbl7u
            N0ZFSQpF0pcwLkttZMHyoyCDEWY+TNC9Yn7zk6JW7lOokxOit86Bcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T18:53:36Z"
    mac: ENC[AES256_GCM,data:UFFlk0OixlvPbEzGvnUWMncxSBEYLmvufcYf8qZT0DUgNBZSG5/wG6DGauPn2LHJ5DyDxwnW7D6I511oHgTBLFAgZT0Rx96wNm3l3p4SilJngDBjK4WaLkz27vyRfX4WOlWdyUBQSwda/RI/BfVNrXrio0MKSYW8HeNT39xkoao=,iv:Fa2Co3fmG/WV/pZKIp24sT/5K2e3nPqyrdJztqnIHas=,tag:J/1dDECN9doTi7AQ4TIiJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
