kind: Secret
apiVersion: v1
metadata:
    name: publications-service-secrets
    namespace: staging-apps
stringData:
    APP_DEBUG: ENC[AES256_GCM,data:UA==,iv:oSMzf5bJhmqVZM83iSig/javpaJXcp1aJohWFhY0Lao=,tag:FjPUv5PXZduZ+n0Q0RkGzg==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:kiwtitw/2Q==,iv:3MtMVOt7D3FsC5LF9E3HE42H/M1XWPSQSxiS+kpOR+g=,tag:Slc9PnJYxMrbHCHOypFk7w==,type:str]
    APP_HOST: ENC[AES256_GCM,data:sDcm76FfOgV0Bs5zTiSx8fUBM1U9KsrFCiz6eaNCMAXjJ8EEnw==,iv:y0BROBR+SLs6ckIJzoO1xlhc7McV7jlWANi4KOwjFKM=,tag:IAU/abDU0ZwtRKALsa3RSA==,type:str]
    APP_PORT: ENC[AES256_GCM,data:h8LsZQ==,iv:FfOgRn93Pv16wpyU/vfohjpRHNQLLdHxThK2WRcd0uI=,tag:HUNXxvRB0fK6APhGY0WCYw==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:0Xj24g==,iv:0T+kG7xhgjbcXb2NlsCxfZJtzJ3uuPTIzefZ9jiXaj0=,tag:aN+QnhsxCRFQ1MruvDHEXA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:Uss86sBtBhY=,iv:Rzl2eXdV1jd0jyXcPcEZfieFoFhAt3ZiYXVKQI7Hl4Y=,tag:7+JgbXWidZ65NEfYPYhTDw==,type:str]
    DATABASE_HOST: ENC[AES256_GCM,data:qkBlQfU9VAcd7hsoXKuMoJLCiFF2KjyLKWNPHTUY7vXuKrvpig==,iv:Negf+rxGB4A4xil+tW1jA5tu7Jo1NQnlfqLTVusGLKI=,tag:kjHV598AoxVzxXAuGAZN6A==,type:str]
    DATABASE_PORT: ENC[AES256_GCM,data:qCWNYA==,iv:1Rk/jGGQIvm+9iZ34WDkbsw0Ruhw8k5ZAPvAnwAHONs=,tag:KZjya9UbloPdTcE1P1ykxg==,type:str]
    DATABASE_NAME: ENC[AES256_GCM,data:2UUca24mlJb8RTEnJ3aKohWolXE=,iv:a0qHSLNOcibPKhD7O/eytLk+cFH7dXTCzbL00/+PrSQ=,tag:2y1FFuz3Z8y9rxxnrRiIvw==,type:str]
    STORAGE_HOST: ENC[AES256_GCM,data:jw7B20ZG1AF0yA0pL2HzZ+5CBGgvh57kLaVCBXLfy+jycNVxfLZ6WtnmPEE=,iv:mITs6wa6zK2wKqwJczU6OFvLAaAS00TkUjsTG8wOdRk=,tag:3+TXWXG9CN+zjBaWmAF0sw==,type:str]
    STORAGE_PORT: ENC[AES256_GCM,data:YM4Dlg==,iv:1dg6iO/JMUlOb1kaUWgiJMrLDs4msi9d0Qok5AaW8ns=,tag:zVx8xMC7TS/fFF7wCq9ZgA==,type:str]
    STORAGE_USER: ENC[AES256_GCM,data:FVVhKQ==,iv:mkk5GWVgveru3By8MjczptQ9+iqsVb9jjoDp0J4tnAI=,tag:CvRM75gSi+KCoOJAGBskKg==,type:str]
    STORAGE_PASSWORD: ENC[AES256_GCM,data:kA4Cyepp/RY=,iv:3NbI0b6RFHGIdfeCyzfzKt1r/0Z2kMluVZqqzJ/aEkY=,tag:W/KU797tNawc33s49bJnjw==,type:str]
    STORAGE_NAME: ENC[AES256_GCM,data:w23uh/XcyTO6gTk4VVzQqOYBOos=,iv:gtgPqy1ACk4hjA+YGVMFRagyYwMr2raloH3Ok4ZTjUY=,tag:mMEhmne3Lql/2LUh/hnfEw==,type:str]
    STORAGE_SERVICE_NAME: ENC[AES256_GCM,data:Uvk=,iv:FxV9dW9+AqFJukCZXFIqpF61H9CO+Gvwjvg74hhDIu8=,tag:TZgqYdDY2XUVuV1zlMF9Bg==,type:str]
    MESSAGE_BROKER_HOST: ENC[AES256_GCM,data:Zn9hozyn0iFd+7mkGlsY8W6Y3Y1CTBdBJwjFTCisr9TNKehr3w==,iv:8ZzlZ4hqLXTOz0S3jggPnBplEIMtQI0wjUmqM1caEyY=,tag:f7cOAV1VdXncPjBwkJ2LjA==,type:str]
    MESSAGE_BROKER_PORT: ENC[AES256_GCM,data:8duNmw==,iv:Q4Mg6ZRZ0rkAYfISPwrbLY8fqMRZ9Rgc2io7VHkzHmk=,tag:/3KnO0HQ8xTPbowq+0UFhw==,type:str]
    MESSAGE_BROKER_MANAGEMENT_PORT: ENC[AES256_GCM,data:VGUNLkk=,iv:hhFshUvBIO3lApNDUmGHpc9xryinfLaEpxKGcKYMQ60=,tag:RUMqpJIgcogfh+uMPP7sEQ==,type:str]
    MESSAGE_BROKER_USER: ENC[AES256_GCM,data:G2czcw==,iv:Iyu3kWnTgVFgySkr6vKRUWFAnJw5BODDg6qUJyBjpPI=,tag:XUsK8yz3kZQRU+SowNqQtQ==,type:str]
    MESSAGE_BROKER_PASSWORD: ENC[AES256_GCM,data:quU4BjcGIaA=,iv:8WXcxa92xiyAkTF2YhHCJN1L7roY5jwtaTVzTEhyHSQ=,tag:DUSn3S/kt5jfyaproXl5tQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Mwkvr9OE4OmBHabEZsHmSpxWAAW3UQlwEtwyZ05AMjk=,iv:UWLnH9jfWN8v4GwtRWPBQNOvkIOw375gcpYAyFs8d2A=,tag:oOGAEgENBl9MuNmE+bUjrQ==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:ebwU44k=,iv:2v2NHKpdiywmXwEkao/N3xA6Qq/h52AsAF6u14X1zKc=,tag:mMR5Qf0ZkynaQYWc36x9LA==,type:str]
    LOKI_PORT: ENC[AES256_GCM,data:9mqSHA==,iv:p/LXtNLP7y5spXgIUUAeRrkw3pI5ztmINcD0EXJTdvs=,tag:tS+7NGoejew56aCYMoLJKA==,type:str]
    TEMPO_PORT: ENC[AES256_GCM,data:9D3gMA==,iv:n+uHJ/XeFFe4Hy8MdzOknPi+ti6lrH2E54L8W2XfMQM=,tag:HPRRiSnCttpTao7SFQeApw==,type:str]
    TEMPO_RECEIVER_GRPC_PORT: ENC[AES256_GCM,data:SWn1xA==,iv:eqr2lfUKMuSAtxoqGb5KFCKcQVhfzJrBYsBNtsR8tFU=,tag:v6bPOgRqxX54BAsPh82Q+w==,type:str]
    TEMPO_RECEIVER_HTTP_PORT: ENC[AES256_GCM,data:stM5tA==,iv:owUWshQhdoM1Kc2JKWJy44O/eiUfgCfGf8ZVSLhLf2k=,tag:0DI5wS6/dpzJyu6UV6pEwQ==,type:str]
    ALLOY_PORT: ENC[AES256_GCM,data:zJp6H1w=,iv:+ZVCOD/ZmY4OBzuUjrmVdtnm1WgVXA2xFp49XOpUIEI=,tag:UMpJBvE9OYt9HOlgk3kfGA==,type:str]
sops:
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOEo1ZEc3bVJUUjJkRnM4
            TFRZU3o4ODFnL3VRaSsrcU5vcnA4S1B6REgwCnhCeElvNm0wRk9ON0Nhc1creXNk
            eVkwaW0vNU9VMUlNVWNZOXhaYnEzN2MKLS0tIFpyLzh3R2greVpPZHlPOXRBZHh4
            OXMyQnZ2dXl0L2ZIaXllMGdYbW90ZVkKe9YxUDXXPE/Gws/T3qwT9Yg41d/zDzRH
            1+ZklpxYBOgxmSGVQuBt170hHtUmV+eU5mo+u6fung5/1p06/uh+SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T13:36:53Z"
    mac: ENC[AES256_GCM,data:/3q4ZIQBGpndBUFFWpNZ0nStLFvM6lBFejQwB+YetfBJDMf0o1XzU8WFajGRhX2X+LgAUxsG4P2I7u2GESBpgFnL1tDpg21V1GkbOTmrWYJCD+ysFNbRkvUOnZ5XlRA7k2ntZJmZv5y3sYgXtQSJfktZVhpDNhvqyAJRsA0zj6w=,iv:aKD6BTO0HmovGO6bUR1Odd8f1RkXJWu5gQ9RuYJ9uO8=,tag:pyVUwKTXRNzsngMDP74aww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
