"""article idempotency key as unique key

Revision ID: 098b01f5de90
Revises: cb7383465655
Create Date: 2026-02-28 20:13:46.580533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098b01f5de90'
down_revision: Union[str, Sequence[str], None] = 'cb7383465655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_idempotency_key'), table_name='articles')
    op.create_index(op.f('ix_articles_idempotency_key'), 'articles', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_idempotency_key'), table_name='articles')
    op.create_index(op.f('ix_articles_idempotency_key'), 'articles', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###
