"""add articles table

Revision ID: 2de2ea6cae99
Revises: 9982c4054295
Create Date: 2026-03-01 19:58:49.719286

"""
import sqlalchemy as sa

from typing import Union, Sequence
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2de2ea6cae99'
down_revision: Union[str, Sequence[str], None] = '9982c4054295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('publication_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_idempotency_key'), 'articles', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_articles_publication_id'), 'articles', ['publication_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_publication_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_idempotency_key'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
