"""add uploads table

Revision ID: 3d95b4989da7
Revises: 2861cba30439
Create Date: 2026-03-01 19:56:59.621920

"""
import sqlalchemy as sa

from typing import Union, Sequence
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '3d95b4989da7'
down_revision: Union[str, Sequence[str], None] = '2861cba30439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='upload_status'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_uploads_status'), 'uploads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_status'), table_name='uploads')
    op.drop_table('uploads')
    # ### end Alembic commands ###

    op.execute('DROP TYPE IF EXISTS upload_status')

