"""add publications table

Revision ID: 9982c4054295
Revises: 3d95b4989da7
Create Date: 2026-03-01 19:58:23.157887

"""
import sqlalchemy as sa

from typing import Union, Sequence
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9982c4054295"
down_revision: Union[str, Sequence[str], None] = "3d95b4989da7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_upload_id'), 'publications', ['upload_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_upload_id'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
