"""add publications table

Revision ID: c5dca57d1eb2
Revises: 407209db1fc3
Create Date: 2026-02-28 16:26:00.057241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5dca57d1eb2'
down_revision: Union[str, Sequence[str], None] = '407209db1fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_source_file_id'), 'publications', ['source_file_id'], unique=False)
    op.alter_column('source_files', 'storage_key',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('source_files', 'storage_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.drop_index(op.f('ix_publications_source_file_id'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
