"""article idempotency key

Revision ID: cb7383465655
Revises: f4ed57567944
Create Date: 2026-02-28 20:01:36.527271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7383465655'
down_revision: Union[str, Sequence[str], None] = 'f4ed57567944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('idempotency_key', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_articles_idempotency_key'), 'articles', ['idempotency_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_idempotency_key'), table_name='articles')
    op.drop_column('articles', 'idempotency_key')
    # ### end Alembic commands ###
