"""unique source_file_id

Revision ID: f4ed57567944
Revises: 5b16e01128aa
Create Date: 2026-02-28 18:45:33.547222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ed57567944'
down_revision: Union[str, Sequence[str], None] = '5b16e01128aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_articles_publication_id'), table_name='articles')
    op.create_index(op.f('ix_articles_publication_id'), 'articles', ['publication_id'], unique=False)
    op.drop_index(op.f('ix_publications_source_file_id'), table_name='publications')
    op.create_index(op.f('ix_publications_source_file_id'), 'publications', ['source_file_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_source_file_id'), table_name='publications')
    op.create_index(op.f('ix_publications_source_file_id'), 'publications', ['source_file_id'], unique=False)
    op.drop_index(op.f('ix_articles_publication_id'), table_name='articles')
    op.create_index(op.f('ix_publication_articles_publication_id'), 'articles', ['publication_id'], unique=False)
    # ### end Alembic commands ###
