"""add publications table

Revision ID: 7e56f1533a8c
Revises: 65f38788b5d2
Create Date: 2026-02-27 15:54:36.426616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e56f1533a8c'
down_revision: Union[str, Sequence[str], None] = '65f38788b5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('upload_id', sa.UUID(), nullable=False),
    sa.Column('xml_file_name', sa.String(length=255), nullable=False),
    sa.Column('article_id', sa.String(length=100), nullable=True),
    sa.Column('id_materia', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('ementa', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id', 'xml_file_name', name='uq_publications_upload_xml')
    )
    op.create_index(op.f('ix_publications_upload_id'), 'publications', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_upload_id'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
